In [1]:
import numpy as np
import random

### Часть 1: Создание и базовые операции с массивами

#### Создание массивов:

- Создайте одномерный массив из 10 случайных целых чисел в диапазоне от 1 до 100.
- Создайте двумерный массив размером 5x5, заполненный случайными числами с плавающей точкой от 0 до 1.
- Создайте массив из 20 равномерно распределенных чисел между 0 и 5. (Используйте функцию `linspace`)
- Создайте массив из 20 целых чисел и преобразуйте его в двумерный массив размером 4x5.

#### Базовые операции:

- Найдите сумму всех элементов в каждом из созданных массивов.
- Найдите среднее значение элементов в каждом из массивов.
- Найдите максимальное и минимальное значения в каждом из массивов.

In [44]:
a = np.random.randint(1, 101, size=10)
a

array([63, 99, 35, 10,  3, 46, 22, 94, 65,  7])

In [45]:
b = np.random.rand(5, 5)
b

array([[0.24361296, 0.13952781, 0.85038383, 0.24836362, 0.20363856],
       [0.94164957, 0.61191139, 0.18544654, 0.48354949, 0.49283108],
       [0.8686264 , 0.6904769 , 0.9060107 , 0.67048408, 0.60702003],
       [0.78913702, 0.06770154, 0.23956639, 0.28599332, 0.1338412 ],
       [0.55361928, 0.54396467, 0.56570633, 0.89426066, 0.80406105]])

In [46]:
c = np.linspace(0, 5, 20)
c

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [47]:
arr = np.arange(1, 21)
d =  arr.reshape(4, 5)
d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [48]:
arrays = {'a': a, 'b': b, 'c': c, 'd': d}

for name, array in arrays.items():
    print(f"Сумма массива {name}: {array.sum()}")
    print(f"Среднее значение элементов массива {name}: {array.mean()}")
    print(f"Максимальное значение массива {name}: {array.max()}")
    print(f"Минимальное значение массива {name}: {array.min()}")
    print()

Сумма массива a: 444
Среднее значение элементов массива a: 44.4
Максимальное значение массива a: 99
Минимальное значение массива a: 3

Сумма массива b: 13.021384423554801
Среднее значение элементов массива b: 0.5208553769421921
Максимальное значение массива b: 0.9416495683281171
Минимальное значение массива b: 0.06770154303521236

Сумма массива c: 50.0
Среднее значение элементов массива c: 2.5
Максимальное значение массива c: 5.0
Минимальное значение массива c: 0.0

Сумма массива d: 210
Среднее значение элементов массива d: 10.5
Максимальное значение массива d: 20
Минимальное значение массива d: 1





### Часть 2: Индексация и срезы

- Из одномерного массива выберите все элементы, которые больше 50.
- Из двумерного массива выберите элементы, которые находятся в четных строках и нечетных столбцах.


- Из одномерного массива выберите элементы с 3 по 7 индекс.
- Из двумерного массива выберите подмассив размером 3x3, начиная с элемента в позиции (1,1).



In [54]:
a[a > 50]

array([63, 99, 94, 65])

In [55]:
d[::2, 1::2]

array([[ 2,  4],
       [12, 14]])

In [56]:
a[3:8]

array([10,  3, 46, 22, 94])

In [57]:
b[1:4,1:4]

array([[0.61191139, 0.18544654, 0.48354949],
       [0.6904769 , 0.9060107 , 0.67048408],
       [0.06770154, 0.23956639, 0.28599332]])

#### Часть 3: Операции над массивами

#### Арифметические операции:

- Создайте два одномерных массива из 10 случайных чисел и выполните поэлементное сложение, вычитание, умножение и деление этих массивов.
- Найдите скалярное произведение двух одномерных массивов.

#### Матричные операции:

- Создайте две матрицы размером 3x3 и выполните их матричное умножение.
- Найдите обратную матрицу для одной из созданных матриц.



In [95]:
arr1 = np.random.randint(1, 50, size=10)
arr2 = np.random.randint(50, 101, size=10)

print(arr1, arr2, "\n")

print(f"сложение - {arr2 + arr1}")
print(f"вычитание - {arr2 - arr1}")
print(f"умножение - {arr2 * arr1}")
print(f"деление - {arr2 / arr1}")

[30 43  1 49 45 42 29 49  4  5] [94 59 51 66 81 77 50 80 82 90] 

сложение - [124 102  52 115 126 119  79 129  86  95]
вычитание - [64 16 50 17 36 35 21 31 78 85]
умножение - [2820 2537   51 3234 3645 3234 1450 3920  328  450]
деление - [ 3.13333333  1.37209302 51.          1.34693878  1.8         1.83333333
  1.72413793  1.63265306 20.5        18.        ]


In [96]:
arr1 = np.random.randint(1, 10, size=10)  
arr2 = np.random.randint(1, 10, size=10) 

print(arr1, arr2)

print("Скалярное произведение:", np.dot(arr1, arr2))

[1 6 2 5 5 8 5 1 7 1] [7 4 5 4 8 3 1 8 2 4]
Скалярное произведение: 156


In [97]:
A = np.random.randint(1, 10, size=(3, 3))
B = np.random.randint(1, 10, size=(3, 3))

print("Первая матрица A:\n", A)
print("Вторая матрица B:\n", B)

print("Результат матричного умножения C = A @ B:\n", np.dot(A, B))

Первая матрица A:
 [[4 8 6]
 [1 6 9]
 [8 4 6]]
Вторая матрица B:
 [[2 8 6]
 [7 4 4]
 [6 2 2]]
Результат матричного умножения C = A @ B:
 [[100  76  68]
 [ 98  50  48]
 [ 80  92  76]]


In [99]:
A_inv = np.linalg.inv(A)

print("Обратная матрица для A:\n", A_inv)

Обратная матрица для A:
 [[ 0.         -0.09090909  0.13636364]
 [ 0.25       -0.09090909 -0.11363636]
 [-0.16666667  0.18181818  0.06060606]]



### Часть 4: Анализ данных

- Создание массива:

Создайте двумерный массив размером 5x3, где первый столбец содержит имена клиентов, второй — их возраст, а третий — стоимость ремонта их автомобилей.


- Сортировка массива:

Отсортируйте массив по возрасту клиентов.

- Средние значения:

Найдите средний возраст клиентов и среднюю стоимость ремонта.

Максимальная стоимость ремонта:

Найдите клиента с максимальной стоимостью ремонта.

In [135]:
data = np.array([
    ('Иван', 25, 15000),
    ('Анна', 30, 25000),
    ('Петр', 22, 18000),
    ('Мария', 35, 30000),
    ('Сергей', 28, 22000)
], dtype=object)

# Получаем индексы для сортировки по возрасту (второй столбец)
sorted_indices = np.argsort(data[:, 1])

# Сортируем массив по индексам
sorted_data = data[sorted_indices]

print("Отсортированный массив по возрасту:\n", sorted_data)

print(f"\nСредний возраст клиентов - {data[:, 1].mean()} \nСредняя стоимость ремнота - {data[:, 2].mean()}\n")

# Находим индекс клиента с максимальной стоимостью ремонта
max_cost_index = np.argmax(data[:, 2])

print(f"Максимальная стоимость ремонта {data[max_cost_index, 2]}\nКлиент с максимальной стоимостью ремонта - {data[max_cost_index, 0]}")

Отсортированный массив по возрасту:
 [['Петр' 22 18000]
 ['Иван' 25 15000]
 ['Сергей' 28 22000]
 ['Анна' 30 25000]
 ['Мария' 35 30000]]

Средний возраст клиентов - 28.0 
Средняя стоимость ремнота - 22000.0

Максимальная стоимость ремонта 30000
Клиент с максимальной стоимостью ремонта - Мария
